In [2]:
#1

'''
A Robot moves in a Plane starting from the origin point (0,0). The robot can move toward UP, DOWN, LEFT, RIGHT. 
The trace of Robot movement is as given following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
The numbers after directions are steps. 

Write a program to compute the distance current position after sequence of movements.
'''

def move(up, down, left, right):
    x = right - left
    y = up - down
    return(x,y)

up = input("steps in UP direction: ")
down = input("steps in DOWN direction: ")
left = input("steps in LEFT direction: ")
right = input("steps in RIGHT direction: ")

x, y = move(int(up), int(down), int(left), int(right))

print("Robot position on X-axis is", x)
print("Robot position on Y-axis is", y)




steps in UP direction: 5
steps in DOWN direction: 3
steps in LEFT direction: 3
steps in RIGHT direction: 2
Robot position on X-axis is -1
Robot position on Y-axis is 2


In [10]:
#2

'''
Data of XYZ company is stored in sorted list. Write a program for searching specific data from that list.
'''

# I am assuming the data is only the age of the employees and we want employees above a certain age


age_data = input("Enter age of employees seperated by a space: ")
cut_off = input("Enter cut_off age: ")

age_data_int = list(map(int, age_data.split()))

for age in age_data_int:
    if age > int(cut_off):
        print (age)
    else: continue
        
        
        

Enter age of employees: 10 20 30
Enter cut_off age: 15
20
30


In [27]:
#3

'''
Weather forecasting organization wants to show is it day or night. 
Write a program for such organization to find whether is it dark outside or not.
'''

from time import localtime

h = int(strftime("%H", localtime())) # getting the hour from the current local time

if (h>19 & h<5): # am assuming 7pm to 5am as the night time
    print("Its dark outside")
else: 
    print("Its not dark outside")




Its not dark outside


In [29]:
#4

'''
Write a program to find distance between two locations when their latitude and longitudes are given.
'''

from math import radians, sin, cos, acos

print("Input coordinates of two points(in degrees):")
slat = radians(float(input("Starting latitude: ")))
slon = radians(float(input("Starting longitude: ")))
elat = radians(float(input("Ending latitude: ")))
elon = radians(float(input("Ending longitude: ")))

dist = 6371.01 * acos(sin(slat)*sin(elat) + cos(slat)*cos(elat)*cos(slon - elon))
print("The distance is %.2fkm." % dist)

Input coordinates of two points(in degrees):
Starting latitude: 23
Starting longitude: 50
Ending latitude: 24
Ending longitude: 51
The distance is 150.87km.


In [36]:
#5

'''
Design a software for bank system. There should be options like cash withdraw, cash credit and change password. 
According to user input, the software should provide required output.
'''

print("Please select from the following options","\n1. Cash withdraw", "\n2. Cash credit", "\n3. Change password")

x = int(input("Your choice: "))

if x==1:
    print("This is Cash withdrawl option")
elif x==2:
    print("This is Cash credit option")
elif x==3:
    print("This is Change password option")
else:
    print("Incorrect input")

    

Please select from the following options 
1. Cash withdraw 
2. Cash credit 
3. Change password
Your choice: 2
This is Cash credit option


In [46]:
#6

'''
Write a program which will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and
3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.
'''

r = list(range(2000,3201))

l = list(filter(lambda x : (x%7==0 and x%5!=0),r))

print(l)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [51]:
#7

'''
Write a program which can compute the factorial of a given numbers. Use recursion to find it.
'''

from functools import reduce

x = int(input("Enter a positive integer for factorial calculation: "))

if x>0:
    fact = reduce((lambda x,y: x*y), range(1,x+1))
else:
    fact =1
    
print("Factorial of", x, "is", fact)

Enter a positive integer for factorial calculation: 0
Factorial of 0 is 1


In [66]:
#9

'''
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. 
The element value in the i-th row and j-th column of the array should be i*j. 
Note: i=0,1.., X-1; j=0,1,¡-Y-1.
'''

import numpy

x = int(input("input integral values for x "))
y = int(input("input integral values for y "))

arr = numpy.zeros((x,y))

for i in range(x):
    for j in range(y):
        arr[i][j] = i*j

print(arr)


input integral values for x 3
input integral values for y 5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [78]:
#10

'''
Write a program that accepts a comma separated sequence of words as input and prints the words in a 
comma-separated sequence after sorting them alphabetically.
'''

inp_words = input("Enter comma separated sequence of words: ")

words_list = inp_words.split(',')

words_list_sorted = sorted(words_list)

print('\nThe sorted words are as below:\n')
print(reduce((lambda x,y : x+','+y), words_list_sorted))


Enter comma separated sequence of words: without,hello,bag,world

The sorted words are as below:

bag,hello,without,world


In [96]:
#11

'''
Write a program that accepts sequence of lines as input and prints the lines after 
making all characters in the sentence capitalized.
'''

print("Enter few lines. After each line press enter, once done just press enter to complete the input:") 

lines = []
while True:
    line = input()
    if line:
        lines.append(line)
    else:
        break
text = '\n'.join(lines)

print("The entire input has been made to upper case as below:\n")
print(text.upper())


Enter few lines. After each line press enter, once done just press enter to complete the input:
Hello world
Practice makes perfect

The entire input has been made to upper case as below:

HELLO WORLD
PRACTICE MAKES PERFECT


In [100]:
#12

'''
Write a program that accepts a sequence of whitespace separated words as input and prints the words after 
removing all duplicate words and sorting them alphanumerically.
'''

inp_words = input("Enter space separated sequence of words: ")

words_list = inp_words.split()

words_list_sorted = sorted(set(words_list))

print('\nThe sorted and de-duplicated words are as below:\n')
print(reduce((lambda x,y : x+' '+y), words_list_sorted))

Enter space separated sequence of words: hello world and practice makes perfect and hello world again

The sorted and de-duplicated words are as below:

again and hello makes perfect practice world


In [115]:
#13

'''
Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check 
whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
'''

inp_bin_numbers = input("Enter comma separated 4 digit binary numbers: ")

bin_numbers_list = inp_bin_numbers.split(',')

print('\nThe binary numbers divisible by 5 are:')
list(filter(lambda x: int(x,2)%5==0, bin_numbers_list))

Enter comma separated 4 digit binary numbers: 0100,0011,1010,1001

The binary numbers divisible by 5 are:


['1010']

In [138]:
#14

'''
Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.
'''

s = input("Enter a sentence: ")

x,y=0,0

for i in range(len(s)):
    if (ord(s[i])>=ord('A') and ord(s[i])<=ord('Z')):
        x=x+1
    elif (ord(s[i])>=ord('a') and ord(s[i])<=ord('z')):
        y=y+1
    else: continue

print('\n Count of upper case characters is:', x)

print('\n Count of lower case characters is:', y)



Enter a sentence: Hello world!

 Count of upper case characters is: 1

 Count of lower case characters is: 9
